"""add classification and subclassification to job_listings

Revision ID: aa057c74b513
Revises: cf7f9fc0ffc2
Create Date: 2026-06-16 09:46:03.472823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa057c74b513'
down_revision: Union[str, Sequence[str], None] = 'cf7f9fc0ffc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classification', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('subclassification', sa.Text(), nullable=True))
        batch_op.create_index('idx_job_listings_classification', ['classification'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_listings', schema=None) as batch_op:
        batch_op.drop_index('idx_job_listings_classification')
        batch_op.drop_column('subclassification')
        batch_op.drop_column('classification')

    # ### end Alembic commands ###
