"""initial schema

Revision ID: cf7f9fc0ffc2
Revises: 
Create Date: 2026-06-15 14:07:25.558187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf7f9fc0ffc2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_listings',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('source', sa.Text(), server_default='seek', nullable=False),
    sa.Column('source_job_id', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('company', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('work_type', sa.Text(), nullable=True),
    sa.Column('salary', sa.Text(), nullable=True),
    sa.Column('close_date', sa.Date(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('qualification_requirements', sa.Text(), nullable=True),
    sa.Column('experience_requirements', sa.Text(), nullable=True),
    sa.Column('raw_description', sa.Text(), nullable=True),
    sa.Column('date_scraped', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_job_id', name='uq_job_listings_source_source_job_id')
    )
    with op.batch_alter_table('job_listings', schema=None) as batch_op:
        batch_op.create_index('idx_job_listings_scraped', ['date_scraped'], unique=False)

    op.create_table('profiles',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('visa_status', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('experiences',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('experience_type', sa.Text(), nullable=False),
    sa.Column('on_cv', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('organization', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.create_index('idx_experiences_user', ['user_id'], unique=False)

    op.create_table('job_skills',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('job_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('skill_type', sa.Text(), server_default='hard', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job_listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_skills', schema=None) as batch_op:
        batch_op.create_index('idx_job_skills_job', ['job_id'], unique=False)
        batch_op.create_index('idx_job_skills_name', ['name'], unique=False)

    op.create_table('qualifications',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('qualification_type', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('institution', sa.Text(), nullable=True),
    sa.Column('field_of_study', sa.Text(), nullable=True),
    sa.Column('grade', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('qualifications', schema=None) as batch_op:
        batch_op.create_index('idx_qualifications_user', ['user_id'], unique=False)

    op.create_table('saved_searches',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('work_type', sa.Text(), nullable=True),
    sa.Column('salary_min', sa.Numeric(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('saved_searches', schema=None) as batch_op:
        batch_op.create_index('idx_saved_searches_user', ['user_id'], unique=False)

    op.create_table('skills',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_skills_user_name')
    )
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.create_index('idx_skills_user', ['user_id'], unique=False)

    op.create_table('user_cvs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_cvs', schema=None) as batch_op:
        batch_op.create_index('idx_user_cvs_user', ['user_id'], unique=False)

    op.create_table('experience_skills',
    sa.Column('experience_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('skill_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('experience_id', 'skill_id')
    )
    with op.batch_alter_table('experience_skills', schema=None) as batch_op:
        batch_op.create_index('idx_experience_skills_skill', ['skill_id'], unique=False)

    op.create_table('matches',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('job_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('score', sa.Numeric(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('gaps', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='new', nullable=False),
    sa.Column('cv_used_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cv_used_id'], ['user_cvs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['job_listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'job_id', name='uq_matches_user_job')
    )
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_index('idx_matches_status', ['status'], unique=False)
        batch_op.create_index('idx_matches_user_score', ['user_id', sa.literal_column('score DESC')], unique=False)

    op.create_table('cover_letters',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('match_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('generated_content', sa.Text(), nullable=True),
    sa.Column('edited_content', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='draft', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', name='uq_cover_letters_match')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cover_letters')
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index('idx_matches_user_score')
        batch_op.drop_index('idx_matches_status')

    op.drop_table('matches')
    with op.batch_alter_table('experience_skills', schema=None) as batch_op:
        batch_op.drop_index('idx_experience_skills_skill')

    op.drop_table('experience_skills')
    with op.batch_alter_table('user_cvs', schema=None) as batch_op:
        batch_op.drop_index('idx_user_cvs_user')

    op.drop_table('user_cvs')
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_index('idx_skills_user')

    op.drop_table('skills')
    with op.batch_alter_table('saved_searches', schema=None) as batch_op:
        batch_op.drop_index('idx_saved_searches_user')

    op.drop_table('saved_searches')
    with op.batch_alter_table('qualifications', schema=None) as batch_op:
        batch_op.drop_index('idx_qualifications_user')

    op.drop_table('qualifications')
    with op.batch_alter_table('job_skills', schema=None) as batch_op:
        batch_op.drop_index('idx_job_skills_name')
        batch_op.drop_index('idx_job_skills_job')

    op.drop_table('job_skills')
    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.drop_index('idx_experiences_user')

    op.drop_table('experiences')
    op.drop_table('profiles')
    with op.batch_alter_table('job_listings', schema=None) as batch_op:
        batch_op.drop_index('idx_job_listings_scraped')

    op.drop_table('job_listings')
    # ### end Alembic commands ###
