"""add extraction fields to job_listings

Revision ID: f42bcd31e385
Revises: aa057c74b513
Create Date: 2026-06-17 16:55:35.535991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f42bcd31e385'
down_revision: Union[str, Sequence[str], None] = 'aa057c74b513'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seniority', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('key_responsibilities', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_listings', schema=None) as batch_op:
        batch_op.drop_column('extracted_at')
        batch_op.drop_column('summary')
        batch_op.drop_column('key_responsibilities')
        batch_op.drop_column('seniority')

    # ### end Alembic commands ###
