"""Per-user tuning knobs, stored as a JSON object in ``profiles.preferences``.

One text column rather than a column per setting: the sidebar's "Personalise
metrics" panel is expected to keep growing new options, and a new key here needs
no migration. Unknown keys are preserved on write; missing keys read as their
default. Kept portable (plain TEXT holding JSON), like ``matches.gaps``.
"""

from __future__ import annotations

import json

from sqlalchemy.orm import Session

from app.models import Profile

# Matches at or above this score (0-100) get a cover letter auto-generated by
# the idle loop. Quality gate: a weak match produces a weak letter and wastes an
# LLM call — the user can move it, but 75 is the sensible default.
DEFAULT_AUTO_LETTER_MIN_SCORE = 75

DEFAULTS: dict = {
    "auto_cover_letter_min_score": DEFAULT_AUTO_LETTER_MIN_SCORE,
    # Layer 4 of the search-suggestion pipeline. OFF by default and opt-in from
    # the sidebar: every other layer is pure Python and free, and this is the
    # one that spends an LLM call, so it should never switch itself on. See
    # app/llm/search_refine.py.
    "llm_search_suggestions": False,
    # Cached refine output: {"searches": [...], "match_count": int}. Lives here
    # rather than in its own table because it is small, per-user, and
    # disposable — losing it costs one LLM call.
    "llm_search_suggestions_cache": None,
}


def _load(raw: str | None) -> dict:
    if not raw:
        return {}
    try:
        data = json.loads(raw)
    except (json.JSONDecodeError, TypeError):
        return {}
    return data if isinstance(data, dict) else {}


def get_preferences(db: Session, profile_id: int) -> dict:
    """Stored preferences layered over DEFAULTS."""
    profile = db.get(Profile, profile_id)
    return {**DEFAULTS, **_load(profile.preferences if profile else None)}


def set_preferences(db: Session, profile_id: int, updates: dict) -> dict:
    """Merge ``updates`` into the stored preferences and commit. Returns the result."""
    profile = db.get(Profile, profile_id)
    if profile is None:
        raise LookupError(f"Profile {profile_id} not found")
    stored = {**_load(profile.preferences), **updates}
    profile.preferences = json.dumps(stored)
    db.commit()
    return {**DEFAULTS, **stored}


def get_auto_letter_min_score(db: Session, profile_id: int) -> int:
    value = get_preferences(db, profile_id)["auto_cover_letter_min_score"]
    return value if isinstance(value, int) and 0 <= value <= 100 else DEFAULT_AUTO_LETTER_MIN_SCORE
