"""Per-user tuning knobs, stored as a JSON object in ``profiles.preferences``.

One text column rather than a column per setting: the sidebar's "Personalise
metrics" panel is expected to keep growing new options, and a new key here needs
no migration. Unknown keys are preserved on write; missing keys read as their
default. Kept portable (plain TEXT holding JSON), like ``matches.gaps``.
"""

from __future__ import annotations

import json

from sqlalchemy.orm import Session

from app.models import Profile

# Matches at or above this score (0-100) get a cover letter auto-generated by
# the idle loop. Quality gate: a weak match produces a weak letter and wastes an
# LLM call — the user can move it, but 75 is the sensible default.
DEFAULT_AUTO_LETTER_MIN_SCORE = 75

# The full cover-letter pipeline (checks + revisions, docs/cover-letter-loop-plan.md §6)
# costs ~$0.20 a letter against ~$0.03 for the one-shot, so it runs only on the best
# matches; the 75-84 band keeps the one-shot.
DEFAULT_LETTER_LOOP_MIN_SCORE = 85
LETTER_ENGINES = ("agent", "workflow")  # which pipeline; the agent is the default (2026-10-03)
DEFAULT_LETTER_ENGINE = "agent"
# Side-output tool -> the preference that switches it on (app/llm/letter/side_outputs.py
# reads it from here, so this module needs no LLM imports).
SIDE_OUTPUT_TOGGLES = {
    "answer_screening": "screening_answers_enabled",
    "suggest_learning": "learning_suggestions_enabled",
    "suggest_resume_tweaks": "resume_advice_enabled",
}

DEFAULTS: dict = {
    "auto_cover_letter_min_score": DEFAULT_AUTO_LETTER_MIN_SCORE,
    # Master switch for the full pipeline. Off = every letter is the one-shot writer
    # (app/llm/cover_letter.py) and no tool or agent runs.
    "letter_loop_enabled": True,
    # Matches at or above this get the pipeline; matches between auto_cover_letter_min_score
    # and this get the one-shot. The effective bar is the higher of the two (see
    # letter_settings), so lowering this below the auto-letter score changes nothing.
    "letter_loop_min_score": DEFAULT_LETTER_LOOP_MIN_SCORE,
    "letter_engine": DEFAULT_LETTER_ENGINE,
    # The pipeline's side outputs (plan §5.6, §6), each one extra model call per full run
    # when it has something to work on: résumé notes (mid), learning suggestions for gaps
    # you confirmed (small), answers to screening questions in the ad (mid). Off = no call.
    # The one-shot writer never makes them.
    "resume_advice_enabled": True,
    "learning_suggestions_enabled": True,
    "screening_answers_enabled": True,
    # Layer 4 of the search-suggestion pipeline. OFF by default and opt-in from
    # the sidebar: every other layer is pure Python and free, and this is the
    # one that spends an LLM call, so it should never switch itself on. See
    # app/llm/search_refine.py.
    "llm_search_suggestions": False,
    # How many job pages one "Scan Page" opens (the 1-hop scan, paced at 5s each).
    # User-tunable, but the API hard-caps it (PreferencesUpdate, le=25) — the cap
    # is the Seek access policy's "capped, never removed" rule, not a suggestion.
    "scan_max_pages": 10,
    # Cached refine output: {"searches": [...], "match_count": int}. Lives here
    # rather than in its own table because it is small, per-user, and
    # disposable — losing it costs one LLM call.
    "llm_search_suggestions_cache": None,
    # Retention + profile-drift weighting; semantics and defaults live in
    # app/retention.py, which validates these on read (a bad value falls back
    # to its default rather than breaking the sweep).
    "retention_window_days": 122,
    "retention_floor_matches": 150,
    "screenshot_ttl_days": 30,
    "stale_profile_weight": 0.35,
    # ISO timestamp of the last completed sweep; written by the sweep itself.
    "retention_last_run": None,
    # LLM spend caps (USD), enforced in app/llm/client.py before any mid/strong
    # call; `small` calls are never blocked. Placeholders until llm_usage shows
    # real costs (docs/cover-letter-loop-plan.md Q8). llm_run_budget_usd is the
    # per-letter-run cap, used by the cover-letter agent (not built yet).
    "llm_daily_budget_usd": 5.0,
    "llm_total_budget_usd": 200.0,
    "llm_run_budget_usd": 0.5,
}


def _load(raw: str | None) -> dict:
    if not raw:
        return {}
    try:
        data = json.loads(raw)
    except (json.JSONDecodeError, TypeError):
        return {}
    return data if isinstance(data, dict) else {}


def get_preferences(db: Session, profile_id: int) -> dict:
    """Stored preferences layered over DEFAULTS."""
    profile = db.get(Profile, profile_id)
    return {**DEFAULTS, **_load(profile.preferences if profile else None)}


def set_preferences(db: Session, profile_id: int, updates: dict) -> dict:
    """Merge ``updates`` into the stored preferences and commit. Returns the result."""
    profile = db.get(Profile, profile_id)
    if profile is None:
        raise LookupError(f"Profile {profile_id} not found")
    stored = {**_load(profile.preferences), **updates}
    profile.preferences = json.dumps(stored)
    db.commit()
    return {**DEFAULTS, **stored}


def get_auto_letter_min_score(db: Session, profile_id: int) -> int:
    value = get_preferences(db, profile_id)["auto_cover_letter_min_score"]
    return value if isinstance(value, int) and 0 <= value <= 100 else DEFAULT_AUTO_LETTER_MIN_SCORE


def letter_settings(db: Session, profile_id: int) -> dict:
    """The cover-letter pipeline's settings, each validated: a bad stored value falls
    back to its default instead of breaking the idle loop (the same stance as
    app/retention.py). ``pipeline_min_score`` is the effective bar for the pipeline."""
    prefs = get_preferences(db, profile_id)
    auto_min = prefs["auto_cover_letter_min_score"]
    if not (isinstance(auto_min, int) and not isinstance(auto_min, bool) and 0 <= auto_min <= 100):
        auto_min = DEFAULT_AUTO_LETTER_MIN_SCORE
    loop_min = prefs["letter_loop_min_score"]
    if not (isinstance(loop_min, int) and not isinstance(loop_min, bool) and 0 <= loop_min <= 100):
        loop_min = DEFAULT_LETTER_LOOP_MIN_SCORE
    enabled = prefs["letter_loop_enabled"]
    engine = prefs["letter_engine"]
    # tool -> its toggle; a non-bool stored value reads as the default (on)
    side = [tool for tool, key in SIDE_OUTPUT_TOGGLES.items() if prefs.get(key) is not False]
    return {
        "auto_min_score": auto_min,
        "enabled": enabled if isinstance(enabled, bool) else True,
        "loop_min_score": loop_min,
        "pipeline_min_score": max(auto_min, loop_min),
        "engine": engine if engine in LETTER_ENGINES else DEFAULT_LETTER_ENGINE,
        "side_outputs": tuple(side),  # the side-output tools a new pipeline run may call
    }
